package com.demo.manager.dao;

public class Cat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.colorid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer colorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.locationid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer locationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.characterid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer characterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cat.name
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.id
     *
     * @return the value of cat.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.id
     *
     * @param id the value for cat.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.colorid
     *
     * @return the value of cat.colorid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getColorid() {
        return colorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.colorid
     *
     * @param colorid the value for cat.colorid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setColorid(Integer colorid) {
        this.colorid = colorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.locationid
     *
     * @return the value of cat.locationid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getLocationid() {
        return locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.locationid
     *
     * @param locationid the value for cat.locationid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setLocationid(Integer locationid) {
        this.locationid = locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.characterid
     *
     * @return the value of cat.characterid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getCharacterid() {
        return characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.characterid
     *
     * @param characterid the value for cat.characterid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setCharacterid(Integer characterid) {
        this.characterid = characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cat.name
     *
     * @return the value of cat.name
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cat.name
     *
     * @param name the value for cat.name
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}