package com.demo.manager.dao;

public class Check {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.catid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer catid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.location
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.id
     *
     * @return the value of check.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.id
     *
     * @param id the value for check.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.catid
     *
     * @return the value of check.catid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.catid
     *
     * @param catid the value for check.catid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setCatid(Integer catid) {
        this.catid = catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.location
     *
     * @return the value of check.location
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check.location
     *
     * @param location the value for check.location
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }
}