package com.demo.manager.dao;

public class Color {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column color.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column color.color
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column color.id
     *
     * @return the value of color.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column color.id
     *
     * @param id the value for color.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column color.color
     *
     * @return the value of color.color
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column color.color
     *
     * @param color the value for color.color
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setColor(String color) {
        this.color = color;
    }
}