package com.demo.manager.dao;

import java.util.Date;

public class Feed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.catid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer catid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.time
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.locationid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer locationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.foodid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer foodid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.id
     *
     * @return the value of feed.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.id
     *
     * @param id the value for feed.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.catid
     *
     * @return the value of feed.catid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.catid
     *
     * @param catid the value for feed.catid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setCatid(Integer catid) {
        this.catid = catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.time
     *
     * @return the value of feed.time
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.time
     *
     * @param time the value for feed.time
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.locationid
     *
     * @return the value of feed.locationid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getLocationid() {
        return locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.locationid
     *
     * @param locationid the value for feed.locationid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setLocationid(Integer locationid) {
        this.locationid = locationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.foodid
     *
     * @return the value of feed.foodid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getFoodid() {
        return foodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.foodid
     *
     * @param foodid the value for feed.foodid
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setFoodid(Integer foodid) {
        this.foodid = foodid;
    }
}