package com.demo.manager.dao;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location
     *
     * @return the value of location.location
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location
     *
     * @param location the value for location.location
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }
}