package com.demo.manager.dao;

public class Pos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos.catid
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private Integer catid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pos.location
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos.id
     *
     * @return the value of pos.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos.id
     *
     * @param id the value for pos.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos.catid
     *
     * @return the value of pos.catid
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public Integer getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos.catid
     *
     * @param catid the value for pos.catid
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setCatid(Integer catid) {
        this.catid = catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pos.location
     *
     * @return the value of pos.location
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pos.location
     *
     * @param location the value for pos.location
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setLocation(String location) {
        this.location = location;
    }
}