package com.demo.manager.dao;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.power
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    private Integer power;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.power
     *
     * @return the value of role.power
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.power
     *
     * @param power the value for role.power
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    public void setPower(Integer power) {
        this.power = power;
    }
}