package com.demo.manager.mymapper;

import com.demo.manager.dao.Character;
import com.demo.manager.dao.CharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    long countByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int deleteByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int insert(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int insertSelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    List<Character> selectByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    Character selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int updateByExampleSelective(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int updateByExample(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int updateByPrimaryKeySelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Mon Dec 26 23:37:15 CST 2022
     */
    int updateByPrimaryKey(Character record);
}