package com.demo.manager.mymapper;

import com.demo.manager.dao.Check;
import com.demo.manager.dao.CheckExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    long countByExample(CheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int deleteByExample(CheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int insert(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int insertSelective(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    List<Check> selectByExample(CheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    Check selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int updateByExampleSelective(@Param("record") Check record, @Param("example") CheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int updateByExample(@Param("record") Check record, @Param("example") CheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int updateByPrimaryKeySelective(Check record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check
     *
     * @mbg.generated Thu Dec 15 16:07:49 CST 2022
     */
    int updateByPrimaryKey(Check record);
}